# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/CornellTPU/ip_repo/tpu_top_1_0/src/blk_mem_gen_0/blk_mem_gen_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blk_mem_gen_0 || ORIG_REF_NAME==blk_mem_gen_0} -quiet] -quiet

# XDC: c:/cornelltpu/dmasystem/dmasystem.tmp/tpu_top_v1_0_project/tpu_top_v1_0_project.gen/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc
