# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/isf9/ultra96-practice/build_vivado/simple_base_project/simple_base_project.srcs/sources_1/bd/design_1/ip/design_1_rst_clk_wiz_0_200M_1/design_1_rst_clk_wiz_0_200M_1.xci
# IP: The module: 'design_1_rst_clk_wiz_0_200M_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/isf9/ultra96-practice/build_vivado/simple_base_project/simple_base_project.gen/sources_1/bd/design_1/ip/design_1_rst_clk_wiz_0_200M_1/design_1_rst_clk_wiz_0_200M_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_rst_clk_wiz_0_200M_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/isf9/ultra96-practice/build_vivado/simple_base_project/simple_base_project.gen/sources_1/bd/design_1/ip/design_1_rst_clk_wiz_0_200M_1/design_1_rst_clk_wiz_0_200M_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_rst_clk_wiz_0_200M_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/isf9/ultra96-practice/build_vivado/simple_base_project/simple_base_project.gen/sources_1/bd/design_1/ip/design_1_rst_clk_wiz_0_200M_1/design_1_rst_clk_wiz_0_200M_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_rst_clk_wiz_0_200M_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/isf9/ultra96-practice/build_vivado/simple_base_project/simple_base_project.srcs/sources_1/bd/design_1/ip/design_1_rst_clk_wiz_0_200M_1/design_1_rst_clk_wiz_0_200M_1.xci
# IP: The module: 'design_1_rst_clk_wiz_0_200M_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/isf9/ultra96-practice/build_vivado/simple_base_project/simple_base_project.gen/sources_1/bd/design_1/ip/design_1_rst_clk_wiz_0_200M_1/design_1_rst_clk_wiz_0_200M_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_rst_clk_wiz_0_200M_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/isf9/ultra96-practice/build_vivado/simple_base_project/simple_base_project.gen/sources_1/bd/design_1/ip/design_1_rst_clk_wiz_0_200M_1/design_1_rst_clk_wiz_0_200M_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_rst_clk_wiz_0_200M_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/isf9/ultra96-practice/build_vivado/simple_base_project/simple_base_project.gen/sources_1/bd/design_1/ip/design_1_rst_clk_wiz_0_200M_1/design_1_rst_clk_wiz_0_200M_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_rst_clk_wiz_0_200M_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
